name: smart_road_guide
description: "Smart Navigation App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^10.1.0
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
